version: "3.8"

services:
  auth:
    image: openslides-auth-dev
    restart: always
    depends_on:
      #  - message_bus
      - cache
    environment:
      - CACHE_HOST=cache
      - CACHE_PORT=6379
      - MESSAGE_BUS_HOST=message_bus
      - MESSAGE_BUS_PORT=6379
    volumes:
      - ./auth/src:/app/src
    tmpfs:
      - /app/tmp
    ports:
      - "9004:9004"
  message_bus:
    image: redis:alpine
  cache:
    image: redis:alpine
