app:
    build: .
    environment:
        NODE_ENV: 'development'
        PORT: 5000
    volumes:
        - .:/app
        - /app/node_modules
    ports:
        - '0.0.0.0:5000:5000'
    command: sh -c "mkdir -p build && nodemon --delay 500ms --watch dist ./build/authentication-server.js"

transpiler:
    build: .
    volumes:
        - .:/app
        - /app/node_modules
    command: ['tsc', '-w']
