version: "3"

services:
  auth:
    image: openslides-auth-test
    restart: always
    depends_on:
      - message_bus
      - cache
    environment:
      - CACHE_HOST=storage
      - CACHE_PORT=6379
      - MESSAGE_BUS_HOST=message_bus
    volumes:
      - ./auth/src:/app/src
    ports:
      - "9004:9004"
    networks:
      - auth

  message_bus:
    image: redis:alpine
    networks:
      - auth

  cache:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - auth

  test:
    image: openslides-auth-test
    command: dockerize -wait tcp://auth:9004 -timeout 10s bash -c "npm run test"
    environment:
      - AUTH_URL=http://auth:9004
      - CACHE_HOST=storage
      - CACHE_PORT=6379
      - MESSAGE_BUS_HOST=message_bus
    depends_on:
      - auth
      - cache
      - message_bus
    networks:
      - auth

networks:
  auth:
