version: "3"

services:
  auth:
    image: openslides-auth-dev
    restart: always
    depends_on:
      #  - message_bus
      - storage
    environment:
      - STORAGE_HOST=storage
      - STORAGE_PORT=6379
      - MESSAGE_BUS_HOST=message_bus
      - MESSAGE_BUS_PORT=6379
    volumes:
      - ./auth/src:/app/src
    ports:
      - "9004:9004"
    networks:
      - auth
  message_bus:
    image: redis:alpine
    networks:
      - auth
  storage:
    image: redis:alpine
    networks:
      - auth
networks:
  auth:
