version: "3.8"

services:
  auth:
    image: openslides-auth-dev
    restart: always
    # depends_on:
    #   #  - message_bus
    #   - storage
    environment:
      # - STORAGE_HOST=storage
      # - STORAGE_PORT=6379
      # - MESSAGE_BUS_HOST=message_bus
      # - MESSAGE_BUS_PORT=6379
      - DATASTORE_READER_HOST=reader
      - DATASTORE_READER_PORT=9010
    volumes:
      - ./auth/src:/app/src
    tmpfs:
      - /app/tmp
    ports:
      - "9004:9004"
    networks:
      - auth
      - datastore
  # message_bus:
  #   image: redis:alpine
  #   networks:
  #     - auth
  # storage:
  #   image: redis:alpine
  #   networks:
  #     - auth
networks:
  auth:
  datastore:
    driver: bridge
