name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test-dev-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: create docker dev image
        run: make build-dev

      - name: run check for prettify and lint
        run: make run-check-cleanup

      - name: run tests in docker
        run: make run-tests
